<h1>Index</h1>
<p><?=$this->_v->title?></p>
<pre><?php print_r($_POST); ?></pre>
<?php
$form = new Kata();
$form->formMethods(false, 'POST', false); //' onsubmit="return false;"'
$form->createField('string','<span class="openHidden">Открыть системные настройки</span>');
$form->createField('hidden', 'action', $action);
$form->createField('text', 'url', false, 'URL<sup>*</sup>: ');
// $form->createField('select', 'parent', $list, 'Вложить в<sup>*</sup>: ',0, false, false, 10,true);
// $form->createField('date', 'goal', $r->row['date'], 'Срок исполнения: ');
$form->createField('radio', 'hide', $hideit, 'Отключить страницу: ',0);
$form->setFieldSet('Добавить всписок',0,4);
$form->createField('submit', 'submit', 'Добавить');
$form->createField('button', 'submit', 'Добавить');
$form->display();
?>