

CREATE TABLE IF NOT EXISTS articles (
	id INT NOT NULL AUTO_INCREMENT,
	url VARCHAR(150) NOT NULL UNIQUE,
	keywords VARCHAR(255) NOT NULL,
	author VARCHAR(100) NOT NULL,
	source VARCHAR(150) NOT NULL,
	title VARCHAR(255) NOT NULL,
	preview TEXT NOT NULL,
	body TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	uuid VARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY (id)
);